// Firebase configuration options
// This file is auto-generated by Firebase CLI
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (identical(defaultTargetPlatform, TargetPlatform.android)) {
      return android;
    }
    if (identical(defaultTargetPlatform, TargetPlatform.iOS)) {
      return ios;
    }
    if (identical(defaultTargetPlatform, TargetPlatform.windows)) {
      return windows;
    }
    if (identical(defaultTargetPlatform, TargetPlatform.linux)) {
      return linux;
    }
    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'YOUR_ANDROID_API_KEY',
    appId: 'YOUR_ANDROID_APP_ID',
    messagingSenderId: 'YOUR_MESSAGING_SENDER_ID',
    projectId: 'mkulima-connect',
    databaseURL: 'https://mkulima-connect.firebaseio.com',
    storageBucket: 'mkulima-connect.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'YOUR_IOS_API_KEY',
    appId: 'YOUR_IOS_APP_ID',
    messagingSenderId: 'YOUR_MESSAGING_SENDER_ID',
    projectId: 'mkulima-connect',
    databaseURL: 'https://mkulima-connect.firebaseio.com',
    storageBucket: 'mkulima-connect.appspot.com',
    iosBundleId: 'com.mkulimaconnect.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'YOUR_WINDOWS_API_KEY',
    appId: 'YOUR_WINDOWS_APP_ID',
    messagingSenderId: 'YOUR_MESSAGING_SENDER_ID',
    projectId: 'mkulima-connect',
    authDomain: 'mkulima-connect.firebaseapp.com',
    storageBucket: 'mkulima-connect.appspot.com',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'YOUR_LINUX_API_KEY',
    appId: 'YOUR_LINUX_APP_ID',
    messagingSenderId: 'YOUR_MESSAGING_SENDER_ID',
    projectId: 'mkulima-connect',
    authDomain: 'mkulima-connect.firebaseapp.com',
    storageBucket: 'mkulima-connect.appspot.com',
  );
}

// Import this at the top of files that reference it
import 'dart:io' show Platform;
import 'package:flutter/foundation.dart';

TargetPlatform get defaultTargetPlatform {
  if (kIsWeb) {
    return TargetPlatform.iOS;
  }
  if (Platform.isAndroid) {
    return TargetPlatform.android;
  }
  if (Platform.isIOS) {
    return TargetPlatform.iOS;
  }
  if (Platform.isWindows) {
    return TargetPlatform.windows;
  }
  if (Platform.isLinux) {
    return TargetPlatform.linux;
  }
  if (Platform.isMacOS) {
    return TargetPlatform.macOS;
  }
  throw UnsupportedError('Unsupported platform');
}
